apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeapp
  template:
    metadata:
      labels:
        app: homeapp
    spec:
      containers:
      - name: homeapp
        image: mayur702/mydockfiles:homeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
